# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.16"
    - name: Build and Run coverage
      run: sbt -v -Dfile.encoding=UTF-8 +jacoco
      working-directory: ./smart_greenhouse
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: smart_greenhouse/target/jacoco/report/ 
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
