name: Report

on:
  push:
    branches:
    - "main"
    paths: 
    - "docs/**"
    
jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc
      - name: Create file list
        id: files_list
        run: |
          cd docs
          echo "::set-output name=files::$(printf 'report/%s ' *.md)"
      - name: Convert with pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -o report.pdf
            -F pandoc-citeproc
            --resource-path=report
            ${{ steps.files_list.outputs.files }}
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
