name: ReportPDF

on:
  push:
    
jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc
      - name: Convert with pandoc
      - run:
          cd docs
          pandoc *.md -o result.pdf
      - uses: docker://pandoc/core:2.9

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
