name: ReportPDF

on:
  push:
    
jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc
      - name: Create file list
        id: files_list
        run: |
          cd docs
          echo "::set-output name=files::$(printf 'docs/%s ' *.md)"
      - name: Exporting pdf
        uses: docker://pandoc/core:2.9
        with:
          args: ${{ steps.files_list.outputs.files }} -o result.pdf
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
