name: Report

on:
  push:
    
jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc
      - name: Create file list
        id: files_list
        run: |
          cd docs
          echo "::set-output name=files::$(printf 'docs/%s ' *.md)"
      - name: Convert with pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -o report.pdf
            -F pandoc-citeproc
            --metadata-file=docs/metadata.yml
            --resource-path=docs
            ${{ steps.files_list.outputs.files }}
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
