name: ReportPDF

on:
  push:
    
jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doc
      - run: cd docs
      - uses: docker://pandoc/core:2.9
        with:
          args: "*.md -o result.pdf"
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
